---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer Resources:
    - Github:
        - icon: si-github
          href: https://github.com/GabrielRamosGomes
    
    - Router:
        - icon: router.png
          href: http://192.168.1.1/index.asp
    
    - Docs:
        - icon: homepage.png
          href: https://gethomepage.dev/

    - ChatGPT:
        - icon: chatgpt.png
          href: https://chat.openai.com/

- Favorites:
    - Youtube:
        - icon: youtube.png
          href: https://www.youtube.com/
    
    - Whatsapp:
        - icon: whatsapp.png
          href: https://web.whatsapp.com/

    - Twitter:
        - icon: twitter.png
          href: https://twitter.com/

    - Gmail:
        - icon: gmail.png
          href: https://mail.google.com/mail/u/0/#inbox