---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer Resources:
    - Github:
        - icon: si-github
          href: https://github.com/GabrielRamosGomes
    
    - Router:
        - icon: router.png
          href: http://192.168.1.1/index.asp
    
    - Homepage Docs:
        - icon: homepage.png
          href: https://gethomepage.dev/

    - ChatGPT:
        - icon: chatgpt.png
          href: https://chat.openai.com/

- Favorites:
    - Youtube:
        - icon: youtube.png
          href: https://www.youtube.com/
    
    - Whatsapp:
        - icon: whatsapp.png
          href: https://web.whatsapp.com/

    - Twitter:
        - icon: twitter.png
          href: https://twitter.com/

    - Gmail:
        - icon: gmail.png
          href: https://mail.google.com/mail/u/0/#inbox

    - Google Docs:
        - icon: google-docs.png
          href: https://docs.google.com/document/u/0/

- Sailing the 7 Seas:
    - Megathread:
        - icon: reddit.png
          href: https://www.reddit.com/r/Piracy/wiki/megathread/

    - AnimeKai:
        - icon: /icons/animekai.png
          href: https://animekai.to/home

    - Repack Games:
        - icon: /icons/repack-games.png
          href: https://repack-games.com/
    
    - GOG Games:
        - icon: si-gogdotcom-#dda0dd
          href: https://gog-games.to/

    - MethStreams:
        - icon: /icons/methstreams.png
          href: https://methstreams.ms/
    
    - brocoflix:
      - icon: /icons/brocoflix.png
        href: https://brocoflix.xyz/