---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/


- Access & Security:
    # - Authentik:
    #     href: https://authentik.{{HOMEPAGE_VAR_TAILNET_NAME}}
    #     description: Identity provider and SSO.
    #     icon: authentik
    #     container: authentik-server
    #     widget:
    #         type: authentik
    #         url: https://authentik.{{HOMEPAGE_VAR_TAILNET_NAME}}
    #         key: {{HOMEPAGE_VAR_AUTHENTIK_API_KEY}}
    #         version: 2
    
    - Tailscale:
        href: https://login.tailscale.com/admin/machines
        description: Tailscale admin panel.
        icon: tailscale

    - Vaultwarden:
        href: https://vaultwarden.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Password manager.
        icon: vaultwarden
        container: vaultwarden


    - AdGuard:
        href: https://adguardhome.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: DNS and adblocking.
        icon: adguard-home
        container: adguardhome
        widget:
          type: adguard
          url: https://adguardhome.{{HOMEPAGE_VAR_TAILNET_NAME}}
          username: {{HOMEPAGE_VAR_ADGUARD_USER}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}

- Monitoring:
    - Dockhand:
        href: https://dockhand.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Docker management UI.
        icon: dockhand
        container: dockhand
        widget:
          type: dockhand
          url: https://dockhand.{{HOMEPAGE_VAR_TAILNET_NAME}}
          username: {{HOMEPAGE_VAR_DOCKHAND_USER}}
          password: {{HOMEPAGE_VAR_DOCKHAND_PASSWORD}}

    - Uptime Kuma:
        href: https://uptime-kuma.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Uptime monitoring.
        icon: uptime-kuma
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: https://uptime-kuma.{{HOMEPAGE_VAR_TAILNET_NAME}}
          slug: homelab

    - Gotify:
        href: https://gotify.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Notification server.
        icon: gotify
        container: gotify
        widget:
          type: gotify
          url: https://gotify.{{HOMEPAGE_VAR_TAILNET_NAME}}
          key: {{HOMEPAGE_VAR_GOTIFY_API_KEY}}

    - Speedtest Tracker:
        href: https://speedtest-tracker.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Internet speed monitoring.
        icon: speedtest-tracker
        container: speedtest-tracker
        widget:
          type: speedtest
          url: https://speedtest-tracker.{{HOMEPAGE_VAR_TAILNET_NAME}}
          version: 2
          key: {{HOMEPAGE_VAR_SPEEDTEST_TRACKER_API_KEY}}

- Storage & Utilities:
    - UGREEN DH2300:
        href: {{HOMEPAGE_VAR_NAS_URL}}
        description: NAS management interface.
        icon: sh-ugreen-nas

    - Filebrowser:
        href: https://filebrowser.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Web based file manager.
        icon: filebrowser
        container: filebrowser

    - Immich:
        href: https://immich.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Self-hosted photo and video backup solution.
        icon: immich
        container: immich_server
        widget:
          type: immich
          url: https://immich.{{HOMEPAGE_VAR_TAILNET_NAME}}
          key: {{HOMEPAGE_VAR_IMMICH_API_KEY}}
          version: 2

    - Docmost:
        href: https://docmost.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Self-hosted documentation platform.
        icon: docmost
        container: docmost

    - ConvertX:
        href: https://convertx.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Media converter.
        icon: convertx
        container: convertx

    - Metube:
        href: https://metube.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: YouTube downloader.
        icon: metube
        container: metube

# JELLYFIN STUFF

- Jellyfin Media:
    - Jellyfin:
        href: https://jellyfin.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Media server.
        icon: jellyfin
        container: jellyfin
        widget:
            type: jellyfin
            url: https://jellyfin.{{HOMEPAGE_VAR_TAILNET_NAME}}
            key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
            version: 2
            enableBlocks: true
            enableNowPlaying: false
            enableUser: false
            showEpisodeNumber: false

    - Seerr:
        href: https://seerr.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Request management.
        icon: seerr
        container: seerr
        widget:
          type: seerr
          url: https://seerr.{{HOMEPAGE_VAR_TAILNET_NAME}}
          key: {{HOMEPAGE_VAR_SEERR_API_KEY}}

- Collection Management:
    - Radarr:
        href: {{HOMEPAGE_VAR_RADARR_URL}}
        description: Movie collection manager.
        icon: radarr
        container: radarr
        widget:
          type: radarr
          url: {{HOMEPAGE_VAR_RADARR_URL}}
          key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
          fields:
            - wanted
            - queued
            - movies
    
    - Sonarr:
        href: {{HOMEPAGE_VAR_SONARR_URL}}
        description: TV show collection manager.
        icon: sonarr
        container: sonarr
        widget:
          type: sonarr
          url: {{HOMEPAGE_VAR_SONARR_URL}}
          key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
          fields:
            - wanted
            - queued
            - series

    - Sonarr Anime:
        href: {{HOMEPAGE_VAR_SONARR_ANIME_URL}}
        description: Anime collection manager.
        icon: sonarr
        container: sonarr-anime
        widget:
          type: sonarr
          url: {{HOMEPAGE_VAR_SONARR_ANIME_URL}}
          key: {{HOMEPAGE_VAR_SONARR_ANIME_API_KEY}}

    - Bazarr:
        href: {{HOMEPAGE_VAR_BAZARR_URL}}
        description: Subtitle management.
        icon: bazarr
        container: bazarr
        widget:
          type: bazarr
          url: {{HOMEPAGE_VAR_BAZARR_URL}}
          key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}

- Downloads & Indexers:
    - qBittorrent:
        href: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
        description: Torrent downloads.
        icon: qbittorrent
        container: qbittorrent
        widget:
          type: qbittorrent
          url: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
          username: {{HOMEPAGE_VAR_QBITTORRENT_USER}}
          password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}

    - Prowlarr:
        href: {{HOMEPAGE_VAR_PROWLARR_URL}}
        description: Indexer management.
        icon: prowlarr
        container: prowlarr
        widget:
          type: prowlarr
          url: {{HOMEPAGE_VAR_PROWLARR_URL}}
          key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}

- Releases:
    - Release Calendar:
        icon: mdi-calendar-month
        description: Upcoming movies, TV, and anime.
        widget:
          type: calendar
          view: agenda
          maxEvents: 12
          showTime: true
          previousDays: 1
          integrations:
            - type: radarr
              service_group: Collection Management
              service_name: Radarr
              color: amber
              baseUrl: {{HOMEPAGE_VAR_RADARR_URL}}
              params:
                unmonitored: false

            - type: sonarr
              service_group: Collection Management
              service_name: Sonarr
              color: sky
              baseUrl: {{HOMEPAGE_VAR_SONARR_URL}}
              params:
                unmonitored: false

            - type: sonarr
              service_group: Collection Management
              service_name: Sonarr Anime
              color: violet
              baseUrl: {{HOMEPAGE_VAR_SONARR_ANIME_URL}}
              params:
                unmonitored: false


# QUESTARR STUFF
- Gaming:
    - Questarr:
        href: https://questarr.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Games downloader.
        icon: questarr
        container: questarr
  
    - qBittorrent Games:
        href: https://qbittorrent-games.{{HOMEPAGE_VAR_TAILNET_NAME}}
        description: Torrent downloads for games.
        icon: qbittorrent
        container: qbittorrent-games