---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homelab Dashboard
theme: dark

target: _self
useEqualHeights: true
disableCollapse: true
headerStyle: clean

quicklaunch:
  showSearchSuggestions: true
  searchDescriptions: true
  provider: duckduckgo
  mobileButtonPosition: top-right

background:
  image: /images/background.png
  saturate: 120
  brightness: 40
  opacity: 20

layout:
  Network:
    header: true
    tab: Main
    style: column
    columns: 2

  Management:
    header: true
    tab: Main
    style: column
    columns: 3

  Media:
    header: true
    tab: Main
    style: column
    columns: 2

  ## Jellyfin Tab
  
  Collection Management:
    header: true
    tab: Jellyfin
    style: row
    columns: 4

  Jellyfin Media:
    header: true
    tab: Jellyfin
    style: column
    columns: 2

  Downloads & Indexers:
    header: true
    tab: Jellyfin
    style: column
    columns: 2

  Releases:
    header: true
    tab: Jellyfin
    style: column
    columns: 1