---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homelab Dashboard
theme: dark

useEqualHeights: true
disableCollapse: true
headerStyle: clean

background:
  image: /images/background.png
  blur: sm
  saturate: 120
  brightness: 40
  opacity: 20

layout:
  Network:
    header: true
    style: column
    columns: 2

  Management:
    header: true
    style: column
    columns: 3

  Media:
    header: true
    style: column
    columns: 2


