---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homelab Dashboard
theme: dark

target: _self
useEqualHeights: true
disableCollapse: true
headerStyle: clean

quicklaunch:
  showSearchSuggestions: true
  searchDescriptions: true
  provider: duckduckgo
  mobileButtonPosition: top-right

background:
  image: /images/background.png
  saturate: 120
  brightness: 40
  opacity: 20

layout:
  Access & Security:
    header: true
    tab: Core
    style: column
    columns: 1

  Monitoring:
    header: true
    tab: Core
    style: column
    columns: 1

  Storage & Utilities:
    header: true
    tab: Core
    style: column
    columns: 1

  ## Jellyfin Tab
  
  Collection Management:
    header: true
    tab: Jellyfin
    style: row
    columns: 4

  Jellyfin Media:
    header: true
    tab: Jellyfin
    style: column
    columns: 2

  Downloads & Indexers:
    header: true
    tab: Jellyfin
    style: column
    columns: 2

  Releases:
    header: true
    tab: Jellyfin
    style: column
    columns: 1

  ## Questarr Tab
  Gaming:
    header: true
    tab: Gaming
    style: column
    columns: 1