---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    label: Raspberry Pi
    cpu: true
    cputemp: true
    uptime: true
    disk: /
    memory: true

- resources:
    label: NAS Disks
    expanded: true
    disk:
        - /mnt/nas/filebrowser
        - /mnt/nas/jellyfin
        - /mnt/nas/immich

- search:
    provider: duckduckgo
    target: _self
    showSearchSuggestions: true

- datetime:
    text_size: 2xl
    format:
        timeStyle: short
        hourCycle: h23


