---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    cputemp: true
    uptime: true

- resources:
    disk: /
    memory: true

- search:
    provider: duckduckgo
    target: _self
    showSearchSuggestions: true

- datetime:
    text_size: 2xl
    format:
        timeStyle: short
        hourCycle: h23


