services:  
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: ${SERVICE}
    volumes:
      - /mnt/storage:/srv
      - ./filebrowser_db:/database
      - ./filebrowser_config:/config
    environment:
      - FB_ROOT=/srv
      - FB_DATABASE=/database/filebrowser.db
    restart: always
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=${SERVICE}"
      - "docktail.service.port=80"
      - "docktail.service.service-protocol=https"