services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${SERVICE}
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - ./${SERVICE}-data/config:/app/config
      - ./assets/images:/app/public/images
      - ./assets/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/nas:/mnt/nas:ro
    healthcheck:
      test: ["CMD", "pgrep", "-f", "next-server"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    env_file: # needs to be here so environment variables are available for config templating
      - .env
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=${SERVICE}"
      - "docktail.service.port=3000"
      - "docktail.service.service-protocol=https"
