services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: ${SERVICE}
    network_mode: host
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - ./${SERVICE}-data/work:/opt/adguardhome/work
      - ./${SERVICE}-data/config:/opt/adguardhome/conf
    healthcheck:
      test: ["CMD", "pgrep", "-f", "${SERVICE}"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=${SERVICE}"
      - "docktail.service.port=80"
      - "docktail.service.service-protocol=https"