services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: ${SERVICE}
    restart: always
    volumes:
      - ./${SERVICE}-data:/app/data
    environment:
      - TZ=${TZ}
      - UMASK=0022
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=${SERVICE}"
      - "docktail.service.port=3001"
      - "docktail.service.service-protocol=https"
