services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: ${SERVICE}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Lisbon
    volumes:
      - /mnt/nas/filebrowser/Youtube:/downloads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8081"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: always
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=${SERVICE}"
      - "docktail.service.port=8081"
      - "docktail.service.service-protocol=https"