services:
  docktail:
    image: ghcr.io/marvinvr/docktail:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale:/var/run/tailscale
    environment:
      - TAILSCALE_OAUTH_CLIENT_ID=${TAILSCALE_OAUTH_CLIENT_ID}
      - TAILSCALE_OAUTH_CLIENT_SECRET=${TAILSCALE_OAUTH_CLIENT_SECRET}

  metube:
    image: ghcr.io/alexta69/metube
    container_name: ${SERVICE}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - /mnt/storage/Youtube:/downloads
    depends_on:
      - docktail
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8081"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: always
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=${SERVICE}"
      - "docktail.service.port=8081"