services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: ${SERVICE}
    restart: unless-stopped
    environment:
      - ALLOW_UNAUTHENTICATED=true
    volumes:
      - ./${SERVICE}-data:/app/data
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=${SERVICE}"
      - "docktail.service.port=3000"
      - "docktail.service.service-protocol=https"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s