services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: ${SERVICE}
    environment:
      - HOST_DATA_DIR=/app/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./${SERVICE}-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:3000/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=${SERVICE}"
      - "docktail.service.port=3000"
      - "docktail.service.service-protocol=https"